import React from "react";
import type { AppProps } from 'next/app'
import {Provider} from 'react-redux';
import {store} from '../redux/store';
import '../styles/globals.css';
import Head from "next/head";


function MyApp({Component, pageProps}: AppProps) {
    return (
        <Provider store={store}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={"/favicon.ico"}/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet"/>
            </Head>
            <Component {...pageProps} />
        </Provider>
    )
}

export default MyApp;
