import Head from 'next/head'
import Image from 'next/image'
import Operators from '../data/data.json';
import {OperatorList} from "../components/operator/OperatorList/OperatorList";
import {FooterContainer, MainContainer, Wrapper} from "../styles/main.styles";

export default function Home() {
    return (
        <Wrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <MainContainer>
                <h1>Выберите оператора</h1>
                <OperatorList operators={Operators.operators}/>
            </MainContainer>

            <FooterContainer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
                </a>
            </FooterContainer>
        </Wrapper>
    )
}
