import Head from 'next/head'
import Image from 'next/image'
import {FooterContainer, MainContainer, Wrapper} from "../../styles/main.styles";
import {CustomInput} from "../../components/customInput/CustomInput";
import {Button} from "../../components/button/Button";
import InputMask from 'react-input-mask';
import {useEffect, useState} from "react";

export default function Home() {
    const [userValues, serUserValues] = useState({
        phone: null,
        count: null
    });
    const [isActive, setIsActive] = useState(false);
    useEffect(() => {
        setIsActive(userValues.count && userValues.count)
    }, [userValues]);

    const phoneHandler = (evt) => {
        serUserValues((prev) => ({ ...prev, phone:evt.target.value}))
    }

    const countHandler = (evt) => {
        serUserValues((prev) => ({ ...prev, count:evt.target.value}))
    }

    return (
        <Wrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <MainContainer>
                <h2>Телефон</h2>
                <InputMask mask="+7 (999) 999 99 99" maskChar="_" onChange={phoneHandler}>
                    {(inputProps) =>  <CustomInput  {...inputProps} type="tel" disableUnderline />}
                </InputMask>

                <h2>Сумма</h2>
                <InputMask mask="+7 (999) 999 99 99" maskChar="_" onChange={countHandler}>
                    {(inputProps) => <CustomInput  {...inputProps} type="tel" disableUnderline />}
                </InputMask>
                <Button text={'Оплатить'} isActive={isActive} />
            </MainContainer>

            <FooterContainer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
                </a>
            </FooterContainer>
        </Wrapper>
    )
}
